- worldsave.cpp
When backup files from other tools are present in the region folder
Minutor could hang infinitely while trying to calculate the world
border. This commit completely rewrites the Chunk number from region
file detection code.
This PullRequest closes issue #60
> fix worldsave when backup files are present

- definitions/vanilla_entity.json
Some IDs were spelled wrong:
Mooshroom -> MushroomCow
Minecart -> MinecartRidable
or missing completely:
MinecartSpawner
EnderCrystal
LeashKnot (not stored on disk)
> added/fixed missing/wrong Entity IDs

- definitions/vanilla_ids.json
it seems that the data value can have 8 and 10 for the upper part of
tall flowers/grass
(no idea what caused the double commit)
> fix for double tall flowers

- definitions/vanilla_ids.json
Mob spawn detection was not working on Red Sandstone Slab & Stairs
Added "Upper" variant name for all Slabs.
> fixed bug with Red Sandstone Slab & Stairs

- mapview.cpp
The first step down Y-wise is the biggest difference, additional steps have less impact on the shade.
Visual comparison for the same area of a world:
before:
this PR:
> Changed Depth shading to produce a more visible shade.

- entity.cpp
- mapview.cpp
Now render correctly Entities inside the current depth layer. Before this change, some Mobs may be invisible when the depth slider is at the same level.
(also done some TAB vs. spaces fixes)
> fix Entity rendering depth

- minutor.cpp
This fixes issue #83. Intentionally it should already have been fixed with commit 87c9af5, as this problem is a duplicate of #34. 
The problem seems to be Operation System or Qt version dependand, therefore I added much more check code to handle this problem in any case
> fix for missing .png suffix

- entity.cpp
- entityidentifier.cpp
In case an Entity is not defined in *_entity.json it was not shown in any of the Entity Overlays.
Now unknown Entities are placed in the Others category and therefore can be made visible.
> fix for unknown Entities are not shown as Overlay

- generatedstructure.cpp
Due to wrong check, during parsing of villages*.dat the attribute
"feature" was parsed into a QVariant even when not available. This
generates warning messages on the debugging console.
> fixed bug that spams debug console

- biomeidentifier.cpp
- biomeidentifier.h
- definitions/vanilla_biomes.json
- main.cpp
- mapview.cpp
- mapview.h
- minutor.cpp
- minutor.h
Add a viewing mode in which the color of a block is determined by the biome it is in. It is very similar to Amidst but it is capable of viewing worlds in which terrain was generated across several versions.
> Biome colors

- biomeidentifier.cpp
- biomeidentifier.h
- blockidentifier.cpp
- blockidentifier.h
- definitions/vanilla_biomes.json
- definitions/vanilla_ids.json
- mapview.cpp
Now all definition files use the Qt style color definition. So colors are defined #rrggbb and can also be defined via CSS color names.
The Pre-calculated light spectrum is done similar to Minecraft with 90% scaling per light level instead of YUV linear shading.
> Fix color name usage

- definitionmanager.cpp
- definitionmanager.h
- definitionupdater.cpp
- definitionupdater.h
- minutor.cpp
for HTTPS support a recompile of Qt is necessary (HTTP would work without)
github.com does not provide a LastModification HTTP header response. Therefore the completely changed update code gets the remote definition file, extracts the version string and compares it with the local version.
Automatic update is done only once a week.
This should fix issue #103 at least it does it during my debugging sessions.
(contains also some name refactoring to align naming of objects through the code)
> Fix automatic definition file update via https

- biomeidentifier.cpp
- biomeidentifier.h
- blockidentifier.cpp
- blockidentifier.h
- chunk.cpp
- chunk.h
- clamp.h
- definitions/readme.txt
- definitions/readme_biomes.txt
- definitions/vanilla_biomes.json
- definitions/vanilla_ids.json
- mapview.cpp
- minutor.pro
Vanilla Minecraft uses different color for plants based on the Biome they grow in. Therefore color of Grass and Leaves change dramatically from Biome to Biome. The code changes introduced here add the same behavior for Minutor. All features are controllable via the definition files.
The feature itself was inspired by [erich666 project Mineways](https://github.com/erich666/Mineways). But development here was completely redone and cross-checked based on 1.10 vanilla source code (mcp931).
To get a visual impression, what changed, here the old style:
and the new Biome based one:
This will close issue #46
> Biome based Grass and Foliage colors

- definitionmanager.cpp
- definitionupdater.cpp
- definitionupdater.h
- mapview.cpp
When debugging the automatic update, all data is present at once. In real-life larger definition files may arrive in smaller parts.
Now also the later arriving parts are handled correctly.
> fix definition update for multi-packet-transfers

- definitions/vanilla_entity.json
- definitions/vanilla_ids.json
I made the following changes:
The entity ID is changed from Ozelot to ocelot in 16w32a
<color> Stained Terracotta is only called <color> Terracotta
Structure Block are now more precise. Colors are based on the average value from the texture
For completeness I added the Structure Void block
Some small questions:
How is your method for defining the colors in the definition file?
Are you planing to reflect the color changes for wool, stayned glass, shulker boxes, etc in 1.12?
Is it possible to add the new colors for the bed?
> Some naming corrections and small additions

- .gitignore
- main.cpp
- minutor.cpp
- minutor.h
- minutor.pro
- pngexport.cpp
- pngexport.h
- pngexport.ui
- settings.ui
- worldsave.cpp
- worldsave.h
With these changes it is possible to define a region to be used for PNG export:
+ it can be set via command line
+ and also with a GUI dialog
+ also the checkerboard patterns are now configurable via this export GUI
Export region is given in Block coordinates, but export is still rounded to complete Chunks.
> add UI dialog to define a bounding box for PNG export

- settings.cpp
- settings.h
The "use default location" was not applied when starting Minutor. This change produces more understandable flow of the settings initialization.
Fixes #93, at least on Windows.
> Settings: Fixed loading and defaults.

- main.cpp
- mapview.cpp
- mapview.h
- minutor.cpp
The look of cave mode can be adapted with these parameters:
* CAVE_DEPTH: number of blocks searched downwards (also slows down Minutor if selected too large, we should consider to implement multi-threading for Block rendering)
* 1/exp(i/(CAVE_DEPTH/2.0)): change the 2.0 to get different shape of exponential curve (flat vs steep). It describes how dark a cave gets rendered depending on the distance to the current level. Deeper caves should get brighter and close to surface caves darker.
* 1.5 * caveshade[i]: use larger factor to get it darker for smaller caves
* std::max(cave_factor,0.25f): to limit the darkness
> implemented cave mode

- chunkcache.cpp
Only use _SC_AVPHYS_PAGES on systems where it exists.  Otherwise fall
back to the default of 10000 chunks.
> Enable compilation on non-Linux unix such as FreeBSD

- blockdata.h
- blockidentifier.cpp
- blockidentifier.h
- chunk.cpp
- chunk.h
- definitionmanager.cpp
- definitionmanager.h
- definitions/readme_biomes.txt
- definitions/vanilla_biomes.json
- definitions/vanilla_blocks.json
- definitions/vanilla_ids.json
- flatteningconverter.cpp
- flatteningconverter.h
- mapview.cpp
- minutor.pro
- minutor.qrc
This is the first approach to be able to load old and 1.13 version maps with the same version of Minutor.
At least here it is working with different maps. Some trillion block definitions are still missing, as Mojang renamed also a lot of blocks: https://minecraft.gamepedia.com/1.13/Flattening#Block_and_Item_IDs
I have added them for grass_block, tall_grass and vine just for test purpose. As they are highlighted and named in Minutor it should be easy to rule that out.
There are several other drawbacks in the new 1.13 definitions and code. I will try to address some of them in the rest of the year, but for now we have same starting point.
* definitions are way from complete, also colors for added blocks are wrong
* performance is very slow, this is probably because of all that strings. I …
> backwards compatible 1.13 translation layer

- blockdata.h
- blockidentifier.cpp
- blockidentifier.h
- chunk.cpp
- chunk.h
- definitionmanager.cpp
- definitions/vanilla_biomes.json
- definitions/vanilla_blocks.json
- definitions/vanilla_ids.json
- flatteningconverter.cpp
- mapview.cpp
I think now we are prepared for 1.13:
+ converter is available to automatically convert old worlds into the new storage format with palette
+ performance is back at previous level
+ definition file handling was improved to get no file clashes
+ all Blocks up to 1.13.1 are entered in the definition file
- not all new Blocks have the correct color, but that can be fixed via definition file updates
> add definitions for missing 1.13 Blocks

- definitions/readme.txt
- definitions/vanilla_blocks.json
- definitions/vanilla_entity.json
- definitions/vanilla_ids.json
This is the complete new color set based on the Vanilla 1.13.1 textures for all known 593 Blocks.
(And also for the new Entities)
I tried to develop automatic color selection rules to be able to reproduce the selected colors. This will also be a big help for new blocks in upcoming Minecraft releases:
* Use the average color of the top side texture for each block (use ImageMagick with box filter to average)
* In case there is an alpha channel in the texture, it is a bit complicated how to average:
+ To get comparable look to the game, I blended Blocks (that typically occur multiple times above each other and get darker with each Block) towards a black background (e.g. leaves and water).
+ Other transparency is used as is (e.g. decorative stuff, glass).
* Ores would vanish in gray, …
> complete color overhaul

- chunk.cpp
- chunk.h
- chunkcache.cpp
- chunkcache.h
- flatteningconverter.cpp
- generatedstructure.cpp
- generatedstructure.h
- mapview.cpp
- mapview.h
- minutor.cpp
- minutor.h
- overlayitem.h
- village.cpp
- village.h
This pull request adds parsing of Structure data inside Chunks.
In my opinion this was the only major missing feature for a 1.13 compatible release.
With Minecraft 1.13 update Structures are no longer stored in extra *.dat files, but as part of Chunks in region files. Storage format is very similar, only the entry NBT key is different. Therefore parsing data can share code between old (tryParseDatFile) and new (tryParseChunk) methods.
Most complicates thing was that Structures now pop up during parsing of Chunks, but are needed in mapview for rendering and minutor for menu creation. This is solved with a very complicated signal slot structure that bubbles up the Structures.
During migration both storage formats will occur in the same world. To prevent duplicate Structures we need a …
> add Structure parsing inside 1.13 Chunks

- definitions/vanilla_entity.json
- entityidentifier.cpp
this replaces pull-request #145
Iron & Snow Golem got renamed and therefore have new IDs.
+ get rid of id1, id2, id* completely
+ for legacy Minutor versions the Entity definitions are duplicated in the definition file
+ for up-to-date Minutor versions all future Entity renaming will be handled in the tag "idlist" which hold a list of strings with all possible names
> fix renamed golems

- blockidentifier.cpp
- definitionmanager.cpp
- definitionmanager.h
This also closes #161
Added an new private method to DefinitionManager to hold all maintenance code regarding definition files. This contains for the moment:
* force delete old hashed names (before Qt5.12 compatibility)
* delete orphaned definitions in settings (matching files were deleted)
* refresh old definitions on disk with build-in definitions (from newer releases)
> repair of definition files

- definitionmanager.cpp
This fixes a weird error that the built-in definitions cannot be installed once the user removes them from the list. The default definition files were copied to the writable cache but not installed; user's attempts to install them then failed with "cannot copy file" error because the file already existed.
After: Any definition file that is about to be installed is first removed from the destination (-> overwrite)
> DefinitionManager: Remove dest file before copying new definitions

- chunk.h
- chunkcache.cpp
- chunkcache.h
- chunkloader.cpp
- chunkloader.h
- chunkrenderer.cpp
- chunkrenderer.h
- mapview.cpp
- mapview.h
- minutor.cpp
- minutor.h
- minutor.pro
- worldsave.cpp
- Fix current implementation for asynchronous Chunk loading. Due to a misplaced mutex unlock we only used one loading thread at the time.
- Move Chunk rendering into own (runnable) class and let it render in global thread pool.
- Use separated thread pools for loading and rendering, as Qt queues tasks in order they arrive. This would result in all loading tasks to be executed before anything gets rendered. By using optimal/2 for loading and optimal thread number for rendering we get 1.5x the number of threads than we have CPU cores. In my opinion this is fine, as loading implies disk activity which stalls the task.
> Asynchronous chunk loading & rendering (using Thread Pool)

- chunk.cpp
- chunkrenderer.h
- definitionmanager.cpp
Fixes the compiler error mentioned in #169
> Fixed clang compile error and some warnings.

- chunkcache.cpp
- chunkcache.h
- chunkloader.cpp
- chunkrenderer.cpp
- chunkrenderer.h
- entity.cpp
- entity.h
- entityidentifier.cpp
- entityidentifier.h
- mapview.cpp
- worldsave.cpp
- worldsave.h
In very seldom cases Minnutor still crashes with memory access
violations:
If a Chunk gets removed from the Cache but still gets loaded or
rendered, the data structure is removed from heap, but still written to.
By using QSharedPointer<Chunk> always some routine has ownership and the
heap is only freed when all routines are finished with processing.
> use shared pointer inside Chunk Cache

- chunkcache.cpp
- chunkcache.h
- mapview.cpp
- mapview.h
When changing depth or other reasons that update the Chunk in
background, the Overlay is overwritten.
By using separated images for the Chunk data and "the rest" (Overlays)
these two categories to not interfere anymore.
Also put Cache usage statistics in status bar when on DEBUG build.
> fix Overlays when changing depth

- biomeidentifier.cpp
- biomeidentifier.h
> Fixed crash on unknown biome.

- biomeidentifier.cpp
- biomeidentifier.h
- do the priority sorting which pack is responsible for what BiomeID once at startup (or at pack change)
- later Biome lookup get a speed-up, as no List has to be parsed anymore
- I was able to measure marginal improvement
This idea was mentioned by @madmaxoft  in #179
> Speedup biome lockup

- chunkrenderer.cpp
- mapview.cpp
- mapview.h
- minutor.cpp
- minutor.h
As sea ground in minecraft gets more and more detailed and interesting, I found a visualization of it in minutor would also make sense. For me it helped to find chests in shipwreck or in the ocean ruins.
Example - you can see the shipwreck on the top only with the sea ground mode:
I added new checkable action menu item which enables / disables the sea ground mode.
> Add render mode for sea ground skipping all liquid blocks

- main.cpp
- mapview.h
- minutor.cpp
- minutor.h
The new View modes (Single-Layer and Sea-Ground-Mode) lack command line switches. The naming was also inconsistent.
+ add missing command line switches
+ use same order at all places
> cleanup view modes

- definitions/vanilla_ids.json
Ran the vanilla_ids.json through a JSON linter, it complained about two extra commas. Fixed those, and used the linter as a formatter, too (thus the `0.0` -> `0` conversion)
> vanilla_ids: Fixed JSON lint errors, formatted.

- chunkcache.cpp
- chunkcache.h
- mapview.cpp
- mapview.h
- settings.cpp
- settings.h
- settings.ui
These changes restrict ZOOM based on available physical RAM and current window size. It should fix all out of memory issues we have at the moment.
Basically possible ChunkCache size is estimated at startup. Only a conservative amount of Chunks is reserved at that moment. Each time the user changes the window size or zooms, the ChunkCache is increased until we reach the initially estimated maximum. In case we hit that boundary, ZOOM is decreased automatically until the amount of visible Chunks matches the Cache again.
To achieve this, the ZOOM behavior was changed to:
* a linear INDEX that is changed by the Mouse Wheel in increments of 1 for each typical scroll event
* a zoom curve TABLE to map a desired zoom factor from the given index
* Positive indices result in the well known zoom IN …
> Restrict zoom based on available memory

- jumpto.cpp
- jumpto.h
- jumpto.ui
Old dialog had no layouts and very ugly resize behavior.
New dialog uses Qt' layouts, so there are no issues with resize.
Dialog's layout was changed to table-like layout, it is more
compact and looks better rather than groups.
Moreover, few GUI only signal-slot connections were moved to .ui
file, so its implementation was dropped from .cpp/.h.
No any logic/control behavior changes were made.
see screenshots below and watch 2 short videos for the difference: [original](https://www.dropbox.com/s/l3nr51b3hc7eo37/Screen%20Recording%202020-01-04%20at%204.01.47%20PM.mov?dl=0), [new one](https://www.dropbox.com/s/hfo5ywpvyx67zli/Screen%20Recording%202020-01-04%20at%205.10.14%20PM.mov?dl=0)
Original Dialog:
Redesigned Dialog:
> redesign JumpTo(Location) dialog

- chunk.cpp
- chunk.h
- mapview.cpp
Significantly improve rendering performance while changing 'depth' (height).
watch these 2 short videos to see the difference: [untouched master version](https://www.dropbox.com/s/4fa05hawrhxo96o/Screen%20Recording%202020-01-04%20at%202.28.15%20PM.mov?dl=0), [my branch](https://www.dropbox.com/s/prryml350w9b5if/Screen%20Recording%202020-01-04%20at%202.29.54%20PM.mov?dl=0)
I loaded pretty small world, on big worlds difference much more significant.
> significantly improve rendering performance

- chunkcache.cpp
DWORDLONG is Windows only type, and it is not defined on Linux.
According to MS documentation, it is unsigned 64 bit integer, so
use Qt' quint64 type instead of this one on any Unix system.
> fixed Linux build - don't use DWORDLONG on unix systems

- minutor.plist
- drop useless key BuildMachineOSBuild
- drop obsolete key CFBundleSignature
- fixed values of [CFBundleDevelopmentRegion](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundledevelopmentregion?language=objc) and [CFBundleName](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-109585)
- updated app version to 2.3.0 (as in sources)
- used [qmake placeholders](https://doc.qt.io/qt-5/qmake-variable-reference.html#qmake-info-plist) for CFBundleExecutable and CFBundleIconFile values
- added missed [recommended keys](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyL …
> updated macOS Info.plist

- minutor.pro
- nbt.cpp
- worldsave.cpp
- zipreader.cpp
it is a bad idea to include local (included in sources) header and link to system library, it may lead to unexpected runtime issues due to slightly different interfaces. (zlib may be not affected by this, it has very stable interface, but all the same it is very bad to do such things)
so use system provided zlib headers and libraries on unix platforms and build zlib sources only on Windows.
> don't include local zlib headers on unix platforms

- chunk.cpp
- chunk.h
- nbt.cpp
- nbt.h
I stumbled across this by chance. I'm pretty sure that the `loaded = true;` needs to be at the very end if this function. 
In addition I extracted the function `Chunk::findHighestBlock` because the code uses a `return` for exiting from multiple nested loops. This would have made it impossible to have the `loaded = true;` at the very end.
I also recognized a random crash in `Chunk::load` caused by `memcpy` of invalid (zero-sized) IntArrayTags. This should at least fix the crash - still there might be an error in the logic of loading
> fix rare rendering bug and improve stability of chunk loading

- chunk.cpp
- chunk.h
- flatteningconverter.h
- paletteentry.h
The extra check for valid Palette entries breaks rendering of old worlds.
(And we both changed the line with boost at the same time...)
> fix rendering of old format worlds

- searchresultwidget.cpp
fixes build error with any GCC compiler:
```
searchresultwidget.cpp: In member function 'void SearchResultWidget::addResult(const SearchResultItem&)':
searchresultwidget.cpp:62:43: error: 'roundf' is not a member of 'std'
item->setText(c++, QString::number(std::roundf(slopeDistance)));
^~~~~~
```
see for details:
- [my OBS project](https://build.opensuse.org/package/show/home:nikoneko:minutor/minutor) (packaging for various Linux systems)
- [Travis CI output](https://travis-ci.org/github/Kolcha/minutor/builds/680991744) (from my fork)
- [AppVeyor output](https://ci.appveyor.com/project/Kolcha/minutor/builds/32529010) for MinGW build (also from my fork)
please setup Travis CI and AppVeyor builds for your repo to prevent such incidents in future, you already have everything required, just …
> add missing include, fix build on Linux

- minutor.pro
fixes warning:
```
Makefile:764: warning: overriding recipe for target 'ui_searchtextwidget.h'
Makefile:760: warning: ignoring old recipe for target 'ui_searchtextwidget.h'
```
> remove duplicated entry from project file

- searchchunkswidget.cpp
don't use QMetaObject::invokeMethod() signature appeared only in Qt 5.10,
use one of signatures available in any Qt version
it produces the same effect as newer, but it is much more portable
even still actual Ubuntu 18.04 has only Qt 5.9, and it is previous LTS
release, so it should be supported
build fails with that error:
```
searchchunkswidget.cpp: In member function ‘void SearchChunksWidget::AsyncSearch::searchLoadedChunk_async(const QSharedPointer<Chunk>&)’:
searchchunkswidget.cpp:113:4: error: no matching function for call to ‘QMetaObject::invokeMethod(SearchChunksWidget*, SearchChunksWidget::AsyncSearch::searchLoadedChunk_async(const QSharedPointer<Chunk>&)::<lambda()>)’
});
^
```
see [Travis CI output](https://travis-ci.org/github/Kolcha/minutor/jobs/681094442) for details, build …
> fix build with Qt 5.9 and older

- .github/workflows/c++qt-crossplattform.yml
This script implements a complete CI workflow on all of our supported operation systems.
+ runs directly on GitHub, no external accounts or services
+ creates also binaries
> add initial CI workflow

- minutor.plist
macOS app compiled with Qt 5.9 is unusable due to invalid values
`Info.plist`: placeholders are not replaced at all.
qmake from Qt 5.9 doesn't support environment variables style `${}`
placeholders in `Info.plist`, only its own `@VAR@` style.
moreover, the set of these placeholders is very limited.
replace `${VAR}` style placeholders with `@VAR@` style guarantee good
support for wide range of Qt versions. such style is supported in
newer versions for backward compatibility.
also dropped `LSMinimumSystemVersion` key because its placeholder is
supported only starting from Qt 5.12, and this key is optional.
> fix macOS app compiled with Qt 5.9

- .github/workflows/c++qt-crossplattform.yml
deploy Qt runtime and package .app into .dmg image making result
app complete and ready to be used by end-users.
unfortunately, archive created by GitHub Actions artifacts upload
step removes top level folder and archives only its content.
this is completely unacceptable, it is even not macOS app from fs
structure point of view despite on that is unusable without Qt...
running `macdeployqt` solves both problems: it integrates required
Qt runtime into .app bundle and also creates .dmg image (but later
it is archived into .zip, ugh..)
> build fully-functional app for macOS

- chunk.cpp
- flatteningconverter.cpp
- flatteningconverter.h
This fixes a bug with the Flattening Converter that could cause ID collisions with IDs from mods. The old "spreading", "shifting", and "virtual ID" algorithms have been changed so they will not generate new internal IDs in the range 0..4095, ensuring that all old-style IDs in that range are usable by both vanilla and modded blocks.
Manually tested on Windows using a 32-bit build, on a 1.12.2 world with a few dozen modded blocks supplied in hand-created JSON files. Prior to the change, some of the modded blocks would show up as obviously wrong (pumpkins instead of ores).
> Avoid legacy ID collisions with virtual IDs for <=1.12.2 worlds

- chunk.cpp
Minutor can crash when attempting to load data from chunks that exist (have an entry in the .mca file) but have not been populated (has a Biomes tag but with no data).
Tested manually on World36 as referenced in issue #192 . Without this change, Minutor crashes when scrolling down on chunk 9, 30 found in file r.0.0.mca. Using NBTExplorer on that file, it shows a chunk with a Biomes tag consisting of 0 integers. I believe this can happen when a chunk is partially created (perhaps due to structures?) but its contents aren't fully generated. With this change the chunk in question loads and is rendered as a black square (distinct from the checkerboard pattern of non-generated chunks), and manually scrolling around the map seemed OK.
> Added check to avoid loading data from chunks with empty Biomes data

- blockidentifier.cpp
- flatteningconverter.cpp
- mapview.cpp
- paletteentry.h
This change causes unknown legacy block IDs to show as unknown (purple) and displays the legacy ID:data in the tooltip.
Tested manually under Windows using the Exp1 world from https://github.com/mrkite/minutor/pull/236. Without the change, note the air gaps (shown as stone) around lava at Y=5, such as around the lava at -72, 250. With the change, note that the lava is surrounded by purple (unknown) blocks with ID 1930:7 (Chisel's plain basalt2 block). Also observe some modded trees with unknown leaf IDs (such as 1759:4) on the surface, such as -41, 200 at Y=75.
This change does NOT deal with unknown post-flattening IDs. I don't currently have any modded post-1.12.2 worlds with which to experiment.
> Unknown legacy block IDs show as such and ID+data is shown in tooltip

- entity.cpp
- entity.h
Comment before Merge!
Villagers have home and job locations (also called POI system).
Also PiglinBrutes use a home location to patrol around a given location.
These changes will draw small indication lines towards these locations.
I took simple blue for bed and red for work, as they differ well from typical block colors.
But I'm open for better color suggestions.
Also another location is possible to highlight: Meeting Point
Example with 4 farmers working in separate houses:
Still open is the dimension. All the locations are stored together with a dimension and should only be drawn when the current rendered dimension is the same.
> Villager poi visualisation

- searchresultwidget.cpp
- searchresultwidget.h
- searchresultwidget.ui
This change adds a button and functionality to write the current search results to a tab-separated file. The change is intended to help with issue #233.
Tested manually under Windows 10 (64 bit), using 32-bit Minutor build and searching for block minecraft:gold_ore in World36 referenced in issue #192. Also searched for entities and exported that data as well.
Caveats:
(1) If a search is in progress, only the current in-progress results will be written.
(2) No attempt is made to extract or impose additional structure on the written data--it's exactly as it appears in the search results, just separated by tabs.
> Added button to export search results to a tab-separated file

- .github/workflows/c++qt-crossplattform.yml
Ubuntu Xenial 16.04 will be end of live in April this year.
We currently have issues installing Qt in the Ubuntu 16.04 CI workflow.
Therefore it should be fine to drop support 2 month early.
(You only have to merge the second commit. Or squash them.)
> remove build for Ubuntu 16.04

- minutor.cpp
Jump To (Dialog Box) was using the same F2 key. Use CTRL+J instead.
Fixes #227
> fix F2 shortcut

- chunk.cpp
- chunk.h
- chunkloader.cpp
- chunkloader.h
With upcoming version 1.17 Entities are stored in a separated folder.
This pull request parses this folder for Entities  also.
Should solve part of #242
> load entities also from extra folder

- blockidentifier.cpp
- blockidentifier.h
- definitions/vanilla_blocks.json
Override for Block solid surface detection to handle top-half Slabs/Stairs correctly during Mob spawn detection.
This was working with old Block IDs as the data can be parsed from the extra bits there.
After "The Flattening" we broke this part of Mob spawn detection.
But somewhat tried to get it back with wrong attributes (rendercube).
With the new attribute we can define the exact Block state for any future Block to enable Mob spawn detection. (Again in definition files and not with extra code.)
> add spawnontop attribute

- .github/workflows/c++qt-crossplattform.yml
- biomeidentifier.cpp
- biomeidentifier.h
- chunk.cpp
- chunk.h
- chunkrenderer.cpp
- definitionmanager.cpp
- definitions/vanilla_biomes.json
- definitions/vanilla_dims.json
- dimensionidentifier.cpp
- dimensionidentifier.h
- generatedstructure.cpp
- labelledslider.cpp
- labelledslider.h
- mapview.cpp
- minutor.cpp
- minutor.h
- searchblockpluginwidget.cpp
- worldsave.cpp
This is the new code to load and parse the Cliffs & Caves NBT data structures and solves most of the #255 topics.
+ Chunk data is parsed also in new locations (no Level Tag anymore, renamed tags)
+ Biomes are also parsed when stored as palette
+ Sections can be in (Block) range -4096 .. +4095 (like for custom dimensions)
+ depth slider is set automatically based on Dimension and version of world
+ depth slider default value can be set via definition files per Dimension (e.g. in The Nether below the ceiling)
+ bug fix: save to PNG crashed at empty region files (1.17 problem)
> support Minecraft 1.18 extended build height

- labelledseparator.cpp
- labelledseparator.h
- minutor.cpp
- minutor.h
- minutor.pro
- minutor.ui
+ flatten Overlay stuff into own menu
Beforehand it was quite tedious to enable/disable many structure overlays. You always had to open 2 sub menu levels where aiming for the second one requires much mouse movement.
Now all Overlays are assembled in an own menu at top level. So they are easier to reach, even as combination of keyboard (Alt+O) and mouse.
+ move all static menu creation into UI designer
All static part of the menu and actions creation is now moved to a from in UI Designer. It is easy to modify the menu there with drag and drop. Only dynamic part of the menu stay in the code: worlds to be loaded, player locations and Overlays
+ fix: clear structure overlay menu on world close
There was a bug, that when closing a world (loading another one), the Structure Overlays where not …
> restructure Overlay menu

- minutor.ui
In some menus we had the same keyboard keys for multiple action items. E.g. "Open world" and "Open" had both "O".
Also some items did not have a keyboard shortcut.
Now keyboard navigation should be more consistent.
> more consistent keyboard navigation in menu

- definitionmanager.cpp
- definitionupdater.cpp
- definitionupdater.h
Previously we used QString::compare() but that fails e.g. 1.6.2 looks "newer" than 1.18.0 as this function compares character by character.
Correct solution is to use our own versionCompare() function (and is already available).
> fix compare of definition file versions

- chunk.cpp
- generatedstructure.cpp
- generatedstructure.h
- properties.cpp
- properties.ui
This changes show spawners in "dungeons" as normal structure overlays. (fixes #146)
From saved file perspective they do not belong to structures, but from user perspective they are also some pre-generated structure found in the world.
It would be possible to parse chests the same way, but some refactoring is necessary before these information can be handled in Minutor.
The properties dialog was also modified:
* set title based on object we show
* disabled the "not used" line edit on top (to be reactivated later)
> Show spawners as overlay

- chunk.cpp
- minutor.pro
see commits messages for details
Ubuntu 16.04 build error
```
[   90s] g++ -c -m64 -pipe -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++1y -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -I. -I../../../include/x86_64-linux-gnu/qt5 -I../../../include/x86_64-linux-gnu/qt5/QtWidgets -I../../../include/x86_64-linux-gnu/qt5/QtGui -I../../../include/x86_64-linux-gnu/qt5/QtNetwork -I../../../include/x86_64-linux-gnu/qt5/QtConcurrent -I../../../include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I../../../lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o chunk.o chunk.cpp
[   92s] chunk.cpp: In member function 'void Chunk::loadLevelTag(const Tag*)':
[   92s] …
```
> fix Linux builds on many systems

- minutor.cpp
At the moment we only support Minecraft worlds stored in a sub-folder called "saves".
This works well with standard installation of Minecraft.
But when worlds are collected at other locations (different folder name), it is not possible to open them directly.
This change should be save, as we only add worlds to the menu when we find the correct files.
> support other folder names for world saves

- chunkrenderer.cpp
- identifier/biomeidentifier.cpp
- identifier/biomeidentifier.h
- identifier/blockidentifier.cpp
Hostile Drowned can spawn in water in Ocean or River Biomes.
This adds an additional spawn check for them.
In case we might miss-detect Ocean or River for future Biomes, a new JSON tag in vanilla_biomes.json is supported to tag that correctly.
> mob spawn highlighting for water mobs

- chunk.cpp
For old versions (before 1.13 "The Flattening") sections that contain only data in upper half are not rendered anymore.
Fix is just to check all Blocks in that Section to judge if it contains data (not lower half) . . .
( fixes #280 )
> fix rendering of only top half filled sections

- definitions/vanilla_dims.json
- identifier/dimensionidentifier.cpp
- minutor.cpp
- minutor.h
- minutor.pro
- nbt/tag.cpp
- nbt/tag.h
- worldinfo.cpp
- worldinfo.h
- zipreader.cpp
- zipreader.h
To support some features we need a place to store information that is common for the complete world. Up to know we only have Definitions which are common to all worlds and Chunk data that is common only to a single Chunk. Some exceptions were solved with extra variables.
(Example features are: World name, Spawn coordinates, last saved data version, Custom Dimensions and Local Difficulty Highlight.)
Here I started to add the class WorldInfo to hold all these world common information.
Then I migrated all the extra complicated stuff, what went smooth.
And tested some custom dimensions, what was working faster then expected.
@mrkite: adding the Custom Dimensions to the menu feels still a bit ugly. Do you have some better idea for that part?
It is the first step to solve #269, #255 and #242. …
> add WorldInfo as central information collection point

- labelledslider.cpp
- labelledslider.h
- mapview.cpp
- mapview.h
- minutor.cpp
The LabelledSlider is used to change the depth setting. Some
touchpads (e.g. on macOS) can send dozens or hundreds of scroll
events per second, each with a very small delta. Unless we keep
track of the "true" state of the slider, these deltas will be lost
when they are rounded into the integer depth setting.
Fixes #287
> Use a double to store state of LabelledSlider

- mapview.cpp
- mapview.h
This changes the way that the current zoom level is stored by the
program. Previously, only the integer index of the zoom level was
stored. This leads to an issue: when you have many scroll events
firing every second, each individual scroll event will only have
a tiny delta. Most of these deltas will not be large enough to
change the zoom level, but they should build up over time. The
previous implementation lost these deltas because of rounding.
With this change, we store the zoom level as a double, and only
convert this to an index (by rounding) when this is needed to
change the scaling factor.
I also fixed a couple of tiny issues:
1. changed delta -> angleDelta to fix QT deprecation warnings.
2. preventing having to call redraw() for every scroll event
Fixes #224
> Store zoom level as a double

- jumpto.cpp
- pngexport.cpp
- pngexport.h
- pngexport.ui
- settings.cpp
This adds a selection to "snap" the export range to Chunks or Regions.
In the past it was silently forced to Chunks, as we only support exporting whole Chunks.
The selection is stored in settings.
Behavior of up/down arrows of spinboxes is controlled to match the selection.
Possible export range is extended to full Region files. (Spinboxes have extended min/max.)
This solves some of the stuff mentioned in #289 
Off topic fix: removed all "question marks" in dialog title bars, as we do not support context help.
> Snap png export to chunk or region

- labelledslider.cpp
#288 introduced a bug: when dragging or clicking the depth slider, the preciseValue was not updated. The next MouseWheel event then jumps the depth slider back to the old position.
Fix is to update preciseValue for all cases the depth slider is moved.
> fix drag & click of depth slider

- identifier/dimensionidentifier.cpp
- identifier/dimensionidentifier.h
- labelledslider.cpp
- minutor.cpp
- worldinfo.cpp
- worldinfo.h
according to discussion in #269 we have to parse Custom Dimensions with a two-step approach:
* A the dimension description always references a dimension_type description.
[Code Refactoring]
Also moves all Dimension menu stuff to WorldInfo to get DimensionIdentifer as clean as all other *Identifiers.
> Two step parsing of custom dimensions

- mapview.cpp
- mapview.h
- settings.cpp
- settings.h
Before this commit, zooming always zooms into the center of the
view. After this commit, we zoom in such a way that the point under
the cursor represents the same location on the map before and after
the zoom. The imitates the behavior of most online mapping tools,
e.g. OpenStreetMaps.
The new zooming approach only applies when using the scroll wheel,
not when zooming with the keyboard. It is also dependent on a
QSetting. If desired, a future commit could expose this setting in
the GUI, making it possible to disable the new zoom behavior.
Fixes #294.
> When zooming with pointing device, zoom into cursor location

- chunk.cpp
- chunkrenderer.cpp
Previously it could happen that the topmost Section of a Chunk does not contain any Block, but light information. In that case we render light and Mob spawning incorrectly.
Fix is mostly to allow also Sections that contain only light data.
To ensure that, the detection method is inverted from "empty" detection to "something found" detection.
> fix light in empty sections

- definitions/readme_biomes.txt
- identifier/biomeidentifier.cpp
- identifier/biomeidentifier.h
fixes #298 
* When using multiple Biome definitions (packs) the index was not guaranteed to be unique, but starting from 0 for each pack.
* Also fix the use of hard encoded Biome IDs for special Biome detection. This was needed for the old format, but does not work after the Cliffs & Caves update.
* update readme for format of Biome definition files
* better way to construct display name out of string ID of Biome (in case of data pack/modded Biomes)
> Fix modded biomes

- identifier/blockidentifier.cpp
- identifier/blockidentifier.h
these 2 commits improve just one function (see its description for details), but the result is impressive - the function became twice faster. and this noticeably affected the whole rendering.
before changes:
after this changes:
and this is what I noticed just looked over the sources... I will look more and likely find more similar prominent places that can be easily optimized. this is just the first step.
> performance optimization: first steps

- mapview.cpp
just a cosmetic changes making the app look better with dark themes on Linux, see attached screenshot
the second commit fixes little artifacts noticeable in the top left corner on the screenshot above
> use QPalette::Base color as backround when nothing to draw

- pngexport.cpp
- pngexport.h
- pngexport.ui
We had a rounding issue when creating the PNG export dialog. The position might be one snap position off the correct one.
Now the next possible "outer" snap position is calculated and used.
Might be related to #289. Add labels that show the Block positions as Chunk or Region index (based on current snap mode):
> Fix PNG export ranges

- minutor.ui
- overlay/properties.ui
- search/searchchunkswidget.ui
- search/searchresultwidget.ui
- search/searchtextwidget.ui
- window title for custom widgets (aka "Form"). it is meaningless and never visible, so useless
- modified but has default value attributes. just to not keep extra info in UI XML files and easy to find changed properties in creator
just a cleanup, no any logic or visual changes
> drop unncessary attributes in .ui files

- chunkrenderer.cpp
- identifier/blockidentifier.cpp
- identifier/blockidentifier.h
mostly cosmetic change rather than something practical, just to follow style. in most places getters are const as they should be, only these 2 classes I found had "unusual" getters (not market as const but const by its nature as it should be)
also, returning non-const references is considered bad practice, and should be avoided, even the Google Code Style Guide that projects follows (as written in README) states that.
> marked a lot of getters in BlockInfo/BlockIdentifier const

- minutor.cpp
- search/searchchunkswidget.cpp
- search/searchchunkswidget.h
- search/searchchunkswidget.ui
- search/searchtextwidget.ui
layout only changes, no logic changed:
- completely new "Search in" block layout
- improved (padding and alignment) "Search for" layout
- set title for search dialogs
macOS
Linux (KDE)
> Search Dialog layout improvement

- search/searchresultwidget.ui
use default font in search results window. now it is too small (especially noticeable in macOS)
> don't set custom font size for search results widget

- mapview.cpp
- settings.cpp
ignore if vertical or horizontal scroll wheel was used when processing scroll wheel events
modifier keys have different name on macOS, so rename the text to reflect that
is part of #319
> Fix macOS modifier keys

- jumpto.ui
just a small cosmetic change, nothing more.
there are no any benefits to have this particular dialog resizable, even it looks strange somehow. and it costs nothing to disable it (just change one property), so why not?
dialog size will be set to `sizeHint()` , so it always will have sufficient size, no worries. even this size depends on platform / theme / some other platform-specific look and feel settings.
> don't allow to resize JumpTo dialog, it is useless

- chunkcache.cpp
macOS does not set `unix` during precompilation, so on a Mac, Minutor was always using a cache of 10,000 chunks. This PR reads the Mac's physical memory size and computes the cache from that instead.
This improves the behavior of https://github.com/mrkite/minutor/issues/319 (but does not completely address it).
> macOS memory management

- identifier/definitionmanager.cpp
- identifier/definitionmanager.h
- eliminate QVariant -> QString conversions (not breaking change, compatible with existing data)
- do not create unnecessary QDir and QFile objects to perform one operation
> DefinitionManager code cleanup

- chunk.cpp
- chunk.h
- chunkrenderer.cpp
- identifier/biomeidentifier.cpp
- identifier/biomeidentifier.h
- mapview.cpp
We had used 8bit to store Biomes per Chunk Section, this is sufficient for Vanilla Minecraft with about 70 Biomes.
This change uses 16bit to store the Biomes, so that mods may add more Biomes than 256.
will fix #325 
Memory impact is negligible as most storage is used for Blocks.
BiomeIdentifier is using 32bit IDs, this change is just the storage format per Chunk Section.
> extend number of usable Biomes to 16bit

- chunk.cpp
- identifier/biomeidentifier.cpp
in case of invalid biome offset previously -1 was returned only
for Debug builds, causing undefined behavior for Release builds.
this is relevant only for Minecraft < 1.18, changed this to the
same as for 1.18+ code - return -1 in invalid case, and print
warning only for Debug builds.
> return -1 for invalid biome offset in any case

- identifier/biomeidentifier.cpp
compiler (GCC 12.2.0) produced warning about some "unmatched" strange Unicode characters on line with comment:
```
../minutor/identifier/biomeidentifier.cpp:134:57: warning: unpaired UTF-8 bidirectional control character detected [-Wbidi-chars=]
134 |     // (below -0.1<U+00B0>C) <U+202D>4C.76.3C<U+202C> or <U+202D>6A.70.39 (above -0.1<U+00B0>C)
|                                                          ~~~~~~~~                             ^
|                                                          |                                    |
|                                                          U+202D (LEFT-TO-RIGHT OVERRIDE)      end of bidirectional context
```
these invisible characters very likely were copied from some web page.
I don't see any reason to keep them in source file and …
> drop strange invisible unicode characters

- chunkrenderer.cpp
For normal rendering we use Biome color of the "highest" Block at each XZ position.
This change adds a new mode (when Biome Color Overlay and Single Layer are both selected):
Then the Biome color is derived from the Block at current Y depth, even when the Block is air.
In case you plan farms or builds in caves or skyblock worlds it is crucial to know the Biome for each Block even at specific depth layer (Biome is height dependent). With this new mode you can analyze Biome layer by layer.
> use Biome color for empty Blocks in single layer

- definitions/vanilla_biomes.json
Biome "The End" was missing a water color definition. This results in gray water for worlds in old storage format.
Will fix #345
> fix water color in The End

- chunkrenderer.cpp
When skipping an empty intermediate Section new Y was set to topmost of next Section and also decremented by for loop. This results in skipping the first Block of the next populated section.
This could happen for pre 1.18 worlds when there are empty Sections in the Chunk. Meaning, something in higher layers, then some empty Sections and also some stuff in lower Sections again.
Will fix #347
> fix skip of Section

- search/searchentityplugin.cpp
In case we select exact pattern search for entities, nothing is found, as the EntityIdentifer stores Entities without the namespace "minecraft:" and possible Entity still have it.
Fix is to remove "minecraft:" namespace from the Entity we try to match.
(This is different for Blocks, as we store the namespace in that case.)
> fix exact pattern search

- mapview.cpp
- minutor.cpp
- minutor.h
Addresses suggestions from #350 
* When a new Structure type is found, the new overlay menu is created at alphabetical correct position instead of simple appending.
* When a structure is from a (non-vanilla) mod, a nested sub-menu is created for that mod. This reduces the amount of entries for each menu.
> Cleaner structure overlay menu

- identifier/biomeidentifier.cpp
- mapview.cpp
- mapview.h
- minutor.cpp
- minutor.h
As reported in #350:
Also sort the overlay sub-menus for mods alphabetically.
Fix modded structures not shown by refactoring the way path and type are used.
Refactor how structures get from Chunk to menu, now they skip the extra step in MapView.
> sort mod menus

- mapview.cpp
This code is designed to prevent zooming past the minimum or maximum, but it doesn't work properly in one important case. When zoom out (zoom levels < 1:1) is enabled via a modifier key, and zoom out has occurred (the current zoom is less than 0), and then the modifier key is released, further attempts to zoom out will instead zoom in as the zoom is snapped to the reduced maximum.
This is observable if you scroll by mistake, but the bigger issue is with high resolution touchpads, when generate numerous scroll events and usually have "momentum", meaning they continue generating scroll events after the user's fingers are off the touchpad. This means the user can do everything "right", and release the modifier key after they stop scrolling, but the momentum scroll events will result in an …
> Fix snapping zoom to minimum when scrolling

- chunk.cpp
- identifier/blockidentifier.cpp
With 1.20 Pitcher Plant,
we have a 2 Block tall flower that should have different color for lower/upper half and for each grow age (0..4)
For lower grow ages the upper half is even invisible.
To get that to work, we have to combine 2 Block properties when defining the Block color.
When searching the correct Block variant from a Palette:
* up to now, we search only for each single property
* but we have to search all combinations, not only one property match
In the definition file it would be nice to give these properties as list.
But older Minutor versions would struggle with that.
The code is implemented, but we should not use it for next couple of years.
> parse all 2x combinations of Block proberties

- overlay/generatedstructure.cpp
Terralith generates a whole bunch of bogus structures under `terralith:zpointer/blahblah` which luckily happen to have zero-sized bounding boxes and, since those wouldn't show up when overlaid anyway, we can ignore them and avoid polluting the Overlay menu at the same time.
> Ignore structures with a zero-sized bounding box

- search/statisticdialog.cpp
When there are less non-air-Blocks on a depth layer than maximum shown Blocks, a blue background is used instead of gray to indicate air. This results in green: searched Blocks, gray: other Blocks, blue: air
> show air in Block Statistic Search

- identifier/biomeidentifier.cpp
the `colors` member variable was not initialized and therefore may contain random content
@Delvin4519 voted for `#000000`, which would be the content for a debug build or cleaned memory.
> init all members of unknownBiome

- identifier/definitionmanager.cpp
don't use [deprecated `QStandardPaths::DataLocation`](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum)
this change requires at least Qt 5.4, but this is not big deal
> QStandardPaths::DataLocation -> QStandardPaths::AppLocalDataLocation

- minutor.cpp
- minutor.h
The "Open World" submenu was not sorted, which could be a big mess with many worlds. Now it is sorted by world name, with the first 9 worlds getting the `Ctrl+<number>` shortcut.
> Sort the Open World sub-menu by world name.

- minutor.cpp
- worldinfo.cpp
- worldinfo.h
Parse all enabled datapacks for their real name (not the filename). Put all found datapacks in a list in WorldInfo, support zipped and unzipped storage. Can be used to query whether a specific datapack is used in that world.
Refactored Custom Dimension parsing into the same code.
Example usage:
Just call e.g. `WorldInfo::isDatapackEnabled("Chunklock")` to query if the datapack (in this case "Chunklock") is used.
> parse datapacks for their name

- minutor.cpp
- minutor.h
Mojang has changed their API (deprecating the part we used in the past)
This PullRequest
1) changes the API entry point to get the player name to a variant that still works.
2) downloads the player skin texture and uses the face as icon in the jump to player menu
All player data is cached and only queried once.
> Fix playname query

- chunk.cpp
- chunk.h
- main.cpp
- mapview.cpp
- mapview.h
- minutor.cpp
- minutor.h
- minutor.ui
This adds a new View option, "ChunkLock", which frames in red all chunks that are currently locked by the [ChunkLock resourcepack](https://modrinth.com/datapack/chunklock):
Also adds a note in the status bar, displaying the item needed for unlocking.
> Added ChunkLock visualisation.

- minutor.pro
- search/searchblockplugin.cpp
- search/searchblockplugin.h
- search/searchchunksdialog.cpp
- search/searchentityplugin.cpp
- search/searchentityplugin.h
- search/searchplugininterface.h
- search/searchresultitem.h
- search/searchresultwidget.h
- search/statisticdialog.cpp
There was a bug that we did not search the topmost layer of each Chunk.
While having the search code open:
* I noticed some C++11 warnings, mentioning detach and copy of Qt containers.
These are solved and we should not unnecessary copy any of the results anymore.
* Found that the search Y-range is not applied during search but the results are filtered afterwards.
Now the search Y-range is taken into account directly during search.
> Fix search in top layer
