mrkite/minutor

main.cpp, minutor.cpp, minutor.h
Extended the command line interface, to allow batch mode .PNG image map generation.
This should close issue #24  
This should close issue #50
=> Extended command line interface

blockidentifier.cpp, blockidentifier.h, mapview.cpp
this will increase render speed by about 3x (when Mob Spawn detection is
switched on)
+ the overhead for mob spawn detection seems to be removed completely!
+ previously the string search was the performance killer
=> Speedup for Mob Spawn detection

main.cpp, minutor.cpp, minutor.h, worldsave.cpp, worldsave.h
- added command line parameters to write the PNG image with a Region and/or Chunk checkerboard pattern
- enhanced command line long parameter parsing: mixed lower and higher case are allowed now
=> added Region & Chunk checkerboard

definitions/vanilla_biomes.json, definitions/vanilla_dims.json, definitions/vanilla_entity.json, definitions/vanilla_ids.json, main.cpp
All BLOCK updates and the new Shulker from Minecraft 1.9.
As additional bonus the definition file updates are now fetched directly from GitHub.
(Something got puzzled in my branch, but I hope everything is sorted the right way now...)
=> Definition update 1 9

entity.cpp, entityidentifier.cpp, entityidentifier.h
before the tool-tip was not showing details for Items anymore
=> Fix item tool-tip after "Update 1.11"

definitions/vanilla_biomes.json
was deleted accidentally during biome overlay coding
=> re-add missing update URL

biomeidentifier.cpp, blockidentifier.cpp, json.cpp
=> Fixed compiler errors

mapview.cpp
Qt an Git(hub) are completely new to me.
Not much C++ experience either.
But it works! :-)
Changed CTRL to ALT+CTRL, because of CTRL + WASD problems.
=> Added accelerator keys suggested in #109

mapview.cpp
I think the zoom factor is not needed.
Also the type of stepSize was wrong before. Without the factor an int should be correct.
=> Removed zoom factor from keyboard movement and did some code clean-up (#109)

jumpto.cpp, jumpto.h, jumpto.ui, mapview.cpp, mapview.h, minutor.cpp, minutor.h, minutor.pro
Sorry, had to do a new pull request.
My original comment:
I finished my vision of the feature I requested in #110.
Please do a code review before considering a merge. I am more of a Java programmer and don't know very much about the pointer stuff in C/C++. There could be some really derpy mistakes. :-)
Also, try it out and give me some feedback about the usability or other things!
=> Implementation of a "Location" window requested in #110

minutor.cpp
There was a copy paste mistake in handling command line parameters.
=> fix setting parameters via command line

chunk.cpp
Minecraft is upgrading/generating Chunks now with much more differnt stages than before. Several data tags are not present in early stages. Minutor was crashing when loading such Chunks.
this fixes #143 and some other possible issues
=> fix loading Chunks that have not populated completely

mapview.cpp, minutor.cpp
=> Restore location on reload & Add y coordinate to status bar

zlib/adler32.c, zlib/compress.c, zlib/crc32.c, zlib/deflate.c, zlib/deflate.h, zlib/gzguts.h, zlib/gzlib.c, zlib/gzread.c, zlib/gzwrite.c, zlib/infback.c, zlib/inffast.c, zlib/inflate.c, zlib/inflate.h, zlib/inftrees.c, zlib/trees.c, zlib/uncompr.c, zlib/zconf.h, zlib/zlib.h, zlib/zutil.c, zlib/zutil.h
there were some security fixes, see: https://zlib.net/
=> update zlib to 1.2.11

definitionmanager.cpp
This would close #149 
Please review the changes carefully !
- Main fix is to add a specific seed (not zero) when doing the hashing during creating file names for the definitions. I took 42 as arbitrary number.
- Remaining problem was that old definition files are still stored in user data folder and registry when first starting the new Minutor version. I created a fixed list with these 5 names and force-delete them before loading anything else. This is not the smartest way, but maybe someone comes up with something better...
=> fix hashing of definition file names for Qt 5.12.x

definitionmanager.cpp
By using a local variable for the definitions in the checkAndRepair method the list of definitions was accidently erased. Now additions are handled correctly.
=> fix adding/repairing definitions

chunkrenderer.cpp, main.cpp, mapview.h, minutor.cpp, minutor.h
I updated the code by [hidroto](https://github.com/hidroto) for a single layer mode ([pull#79](https://github.com/mrkite/minutor/pull/79)). This is for [issue#6](https://github.com/mrkite/minutor/issues/6)
=> Feature single layer mode

chunkrenderer.cpp, main.cpp
also prepare next release number
=> fix compile issues of last merge

chunkcache.cpp
shared pointer to cached chunk needs to be _copied_ from cache before unlocking the mutex
=> fix potential stability problem

.appveyor.yml, .travis.yml
added AppVeyor and Travis CI config files
[AppVeyor build configurations](https://ci.appveyor.com/project/Kolcha/minutor):
- Visual Studio 2017, Qt 5.13.2, 64-bit
- MinGW 7.3.0, Qt 5.13.2, 64-bit
[Travis CI build configurations](https://travis-ci.org/Kolcha/minutor):
- Ubuntu 18.04, GCC 7, Qt 5.9.5
- macOS 10.14, Xcode 11.3, Qt 5.13.2
Closes #182
=> Travis / Appveyor CI

blockidentifier.cpp, blockidentifier.h, chunk.cpp, chunk.h, chunkcache.cpp, chunkcache.h, chunkid.h, mapview.cpp, minutor.pro
refactoring only: extract ChunkID from ChunkCache header
I (slowly) started with bringing the search functionality to master (#199). But this needs some preparation steps. As this work will go over a timeframe of potentially months I want to push any working version in between to master as soon as possible to avoid merging conflicts later. Hope you are not annoyed by many smaller pull requests that doesn't bring functionality nor fixes.
=> preparations for search feature

chunk.cpp
=> support for new BlockStates format comming with 20w17a

chunk.cpp
The old default constructor was initializing the blockLight to all 0s. When writing an own constructor, we have to do something similar.
For performance reasons this should only be done when Chunk data does not contain light data. (So not in the constructor itself)
fixes #226
=> fix light map

generatedstructure.cpp
It seems that with Minecraft 1.17 the BB tag (defining the covered area "Bounding Box") for generated structures is not declared anymore. In these cases the structure contains BB tags only in the Children. Currently Minutor only parses Structures with BB present and skips them otherwise.
Fix is to search for a BB at the Structure definition and when not found to calculate min/max of all children.
=> fix parsing of Structures when BB tag is missing

minutor.cpp, minutor.ui, settings.cpp, settings.h, settings.ui
+ moved "Manage Definitions" into Help menu
+ moved "Check for updates" into Settings dialog (as button)
=> rearrange configuration menu items

minutor.cpp, pngexport.cpp, pngexport.h, worldsave.cpp, worldsave.h
Negative export bounds coordinates did result in wrong image size.
Also some method name refactoring.
=> fix PNG export with negative export region coordinates

chunkrenderer.cpp
... as they where not shown before.
Also the depth gradient was not working at exactly depth -1.
Rest of the changes is just naming refactor and slight performance improvement due to getting code out of the main render loop.
=> fix cave mode for caves below 0

minutor.ui
Removed probably by mistake in #263.
=> Added the Ctrl+D shortcut for Depth Shading.

chunkrenderer.cpp, java.cpp, java.h, main.cpp, mapview.h, minutor.cpp, minutor.h, minutor.pro, minutor.ui, worldinfo.cpp, worldinfo.h
adds a green highlight for Chunks that spawn Slimes
=> add view mode: Slime Chunks

chunk.cpp, chunk.h, chunkrenderer.cpp, main.cpp, mapview.h, minutor.cpp, minutor.h, minutor.ui, worldinfo.cpp
This adds a color overlay with inhabited time per Chunk. It is more-or-less the regional difficulty of the game.
Will close #175 in that issue you can also see some render examples.
=> View regional difficulty

main.cpp, minutor.cpp, minutor.h, worldinfo.cpp
Will fix last remaining topic from #269
Example: minutor --world <path> --dimension <minecraft:the_nether>
would open the world directly with the correct dimension.
=> Command line support for dimension

identifier/definitionmanager.cpp
Some time ago Qt changed the way qHash is used, so we migrated to use 42 as seed. Here we try to detect and remove some more of the old names.
will fix #305
=> fix wrong qHash0 names

identifier/definitionmanager.cpp, mapview.cpp, overlay/entity.cpp, overlay/propertietreecreator.cpp, search/entityevaluator.cpp, search/searchresultwidget.cpp
detected by static code analyzer, worth fixing
=> fixes for issues detected by static code analyzer, worth fixing

minutor.cpp
central widget exists already, it is created in class generated from .ui file
so, there is no need to create new one and replace existing, just setting some layout for it is enough
=> don't create new central widget, just set layout for existing

identifier/definitionmanager.cpp
qHash() doesn't specify some algorithm, so it is not suitable for
permanent data as so as returned value may be changed depending on
Qt version (more correctly on used underlying algorithm)
CRC32 is very lightweight checksum algorithm, so it will not have
significant impact to performance (especially for such small data)
CRC32 implementation is available in Zlib, which is already used in
the project, so it costs nothing using CRC32 implementation from it
=> don't use qHash() for permanent data, use CRC32 instead

worldinfo.cpp
fix for #329
Int is now also supported, even when undefined by Mojang.
Some other elements are now also checked before use.
=> fix crash on wrong type in level.dat

zlib/compress.c, zlib/crc32.c, zlib/deflate.c, zlib/deflate.h, zlib/gzlib.c, zlib/gzread.c, zlib/gzwrite.c, zlib/infback.c, zlib/inflate.c, zlib/inftrees.c, zlib/inftrees.h, zlib/trees.c, zlib/uncompr.c, zlib/zconf.h, zlib/zlib.h, zlib/zutil.c, zlib/zutil.h
we were not effected by this security issue, but update anyway
=> update to zlib 1.2.13

chunkrenderer.cpp
amendment to increase rendering performance
drag out the static part of flag comparison from main loop
=> performance improvement for #341

search/searchblockplugin.cpp, search/statisticdialog.cpp, search/statisticdialog.h
I screwed up the normal search for Blocks feature while refactoring the code...
correct data type for HID is 32bit unsigned integer
=> fix search for Blocks

labelledseparator.cpp, labelledseparator.h, minutor.cpp, minutor.h
implemented tristate checkbox at the beginning of every structures overlays submenu
closes #350
=> Structure Overlays select/deselect all option

worldinfo.cpp, worldinfo.h
instead of description which might be just lengthy text
this is a fix to pull request #371 from yesterday
the namespace of a namespace is definitely unique
=> use namespace of datapack

zlib/LICENSE, zlib/adler32.c, zlib/compress.c, zlib/crc32.c, zlib/deflate.c, zlib/deflate.h, zlib/gzclose.c, zlib/gzguts.h, zlib/gzlib.c, zlib/gzread.c, zlib/gzwrite.c, zlib/infback.c, zlib/inffast.c, zlib/inffast.h, zlib/inflate.c, zlib/inftrees.c, zlib/inftrees.h, zlib/trees.c, zlib/uncompr.c, zlib/zconf.h, zlib/zlib.h, zlib/zutil.c, zlib/zutil.h
Just a copy of all files of latest release from: https://github.com/madler/zlib
=> update to zlib 1.3.1

chunk.cpp, chunk.h, worldsave.cpp
I hope this fixes the new memory leak #381 which is present during PNG save.
=> Fix memory leak
